### ISSUE TITLE
Register of members

### ISSUE THREAD

**Issue by brianteeman** [joomla/volunteers.joomla.org#111]
Apparently the JVP is now being used as a registry of members which is a legal requirement

As such this needs to be specified on the site AND it needs to be clear that it will be used as such and the importance of accurate information etc

> Please fill in your Mailing Address fields, this is required for active Members

This needs to be explained what it means, why it is needed and what are active members

In addition as people rarely have a need to log in and this is a new requirement then it is probably a requirement that this information is communicated to everyone who has an account and not just waiting to see if they randomly log in

**Comment by jeckodevelopment** [comment]
Hi Brian,
yes, the easiest way to comply with the bylaws is to use the Volunteers Portal as official registry of memers of the organisation.
We need to store a physical mailing address for each member of the organisation. And we define members of the org. each volunteer that is registered as "member" or higher level.
Please feel free to suggest a description for that, since it could be easier for you to provide one :)
And, yes, i completely agree we need to send out a communication to all our members to invite them to comply with this requirement.
Maybe @joomv we can send out a newsletter

**Comment by Joomv** [comment]
Will liaise with @sanderpotjer to get ACY running and message all members.
Would be a good opportunity to clean the portal out a bit at the same time.
Leave it with me.

**Comment by brianteeman** [comment]
please dont message people until you have fixed the form - no point collecting even more potentially  invalid information

**Comment by roland-d** [comment]
Related to #143

**Comment by sanderpotjer** [comment]
#143 has been fixed, and notice with reference & link to bylaws change a while ago.
