### ISSUE TITLE
Missing sub-teams under a Leadership

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#18]
We discussed in #17 about moving GSoC project teams under the main "Google Summer of Code Joomla Team": 
https://volunteers.joomla.org/teams/google-summer-of-code-joomla-team
As said, the main team is under OSM responsibility and will become a Program when the new structure will be deployed.

And sub-teams are under PLT responsibility.
At the moment, the modifications on Volunteers Portal reflect the correct situation: main team under OSM, sub-teams under PLT.
But, if you go to https://volunteers.joomla.org/leadership/production-leadership-team#teams 
you will see only "main" teams, and not subteams under PLT responsibility.

Is this an expected behaviour? Should we see all groups and subgroups under a leadership responsibility?

**Comment by sanderpotjer** [comment]
The issue is basically that a subteam leadership should not be able to set differently then the main team "leadership". The new portal is designed in line with the new structure. In the new structure a team will be part of a "department", sub-teams of a team can't be part of another "department". Therefore the subteams are not listed separately under a "leadership/department". 

So the main team: OSM, subteams: PLT setup should not be possible, and this is a rare case. My suggestion would be to set the main team to PLT to, and add a note in the teams description. 

And of course the bug needs to be fixed that the subteams "leadership/department" can be set differently then the main team.

**Comment by jeckodevelopment** [comment]
I can understand your points, thank you :)
The issue is that GSoC will continue on its way being under OSM now and then Program Dept. 
And its subteams are and will be under PLT responsibility. It's (or it could be) an exception.

**Comment by sanderpotjer** [comment]
Another option might be to create another main team for the PLT, besides the one for OSM?

**Comment by jeckodevelopment** [comment]
it could be good

**Comment by sanderpotjer** [comment]
@jeckodevelopment some changes have been made to prevent editing the department. Not sure if I can close the issue now for you?

**Comment by jeckodevelopment** [comment]
I guess it's ok now. I'll check better tomorrow. Let's close. If needed I'll reopen. Thank you Sander
