### ISSUE TITLE
[jvols] 

### ISSUE THREAD

**Issue by maxim-pishnyak** [joomla/volunteers.joomla.org#232]
Volunteers' "Create an account" said: "Thank you for registering. You may now log in using the username and password you registered with."

This is not actually true.

Also username is not on "Create an account" page. And "Login Form" has only email, not "username"

**Comment by jeckodevelopment** [comment]
Hello Maxim,
the username is the email address

**Comment by sanderpotjer** [comment]
@maxim-pishnyak thanks for reporting. Username is now changed into email for that sentence.

**Comment by maxim-pishnyak** [comment]
Thanx @sanderpotjer. 

And what about this stuff?

> Volunteers' "Create an account" said: "Thank you for registering. You may now log in using the username and password you registered with."
> 
> This is not actually true.

Have you tried actually to test registration for Volunteers? Either registration isn't work, or logging in is broken.

**Comment by maxim-pishnyak** [comment]
> Hello Maxim,
> the username is the email address
Yes, @jeckodevelopment, But only if email address could be used during logging in. Probably registering is broken itself.

**Comment by sanderpotjer** [comment]
> Have you tried actually to test registration for Volunteers? Either registration isn't work, or logging in is broken.

No, we don't test. And we added almost 1600 accounts manually. Without jokes, of course it is tested and I actually did another test round two weeks ago. 

I can't find a recent account that looks like it is yours. So probably something went wrong, not sure what and it seems to be specific based on the entered data. Can you give it another test and otherwise let me know what data you entered so we can duplicate the issue. You can use sander [dot] potjer [at] community [dot] joomla [dot] org

**Comment by maxim-pishnyak** [comment]
Entered data sent, @sanderpotjer. Both Chrome and Firefox checked. No registration with still successful message. Maybe user activation wasn't present correctly?
