### ISSUE TITLE
Active state on "My Profile"

### ISSUE THREAD

**Issue by sanderpotjer** [joomla/volunteers.joomla.org#61]
Current active menu is "Joomlers" when clicking on "My Profile".

**Comment by nileshprasad137** [comment]
Hey, I want to work on this issue. I'll soon send a pull request.

**Comment by nileshprasad137** [comment]
Can anyone guide me to solve this issue? I tried to setup the local environment to work , but when i am trying to run "volunteers.joomla.org/www/index.php" , this error is showing up. 
"Error displaying the error page: Application Instantiation Error: Could not connect to MySQL."
I am a beginner contributor to Joomla.

**Comment by sanderpotjer** [comment]
@nileshprasad137 thanks for your interest in contributing! 

Did you setup the sample database locally? And did you added the correct credentials in the configuration.php so it is using your local database?

**Comment by nileshprasad137** [comment]
@sanderpotjer Thanks for that suggestion. I had messed up credentials in configuration.php. 

However , I am still confused because there is no folder for "my-profile" , so when I enter  the correct credentials for Sample User Account as mentioned in the "readme" file, it redirects me to "My-profile" page which is not available . After entering back button , it redirects me here. 
![issue61](https://cloud.githubusercontent.com/assets/16336390/22860262/765868da-f11e-11e6-8713-ba12b5f1e13e.PNG)

So, my question is ,  where should I look for the code for the menu bar as I just need to change the "li" state to "current-active" ?
Sorry , if I may sound a bit foolish , but I am a bit confused here and i need a bit guidance to get started contributing.

**Comment by mbabker** [comment]
I don't think you can fix this.  Clicking the "My Profile" link issues a 303 from https://volunteers.joomla.org/my-profile to https://volunteers.joomla.org/joomlers/83-michael-babker (replace the last segment with your individual profile).  So you aren't actually on a "my profile" page at any point.

If you really wanted to fix this, you'd either have to not redirect the `my-profile` route or hook the `onAfterRoute` event to change the active menu item if you don't remove the redirect.

**Comment by sanderpotjer** [comment]
This has now been implemented
