### ISSUE TITLE
[v.j.o] Add Github Handles to all team members 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/volunteers.joomla.org#69]
It would be very useful to have github handles for all people in teams so they can be looked up and called on from github - so they can be alerted or tasked items. 

E.g. https://github.com/joomla/joomla-cms/pull/13230#issuecomment-267352690

**Comment by sanderpotjer** [comment]
@PhilETaylor I'm not sure if this is what you are looking for, but the GitHub handles are already available. Check your own profile for example:
<img width="918" alt="github" src="https://cloud.githubusercontent.com/assets/522834/22043354/7b2360fe-dd0f-11e6-9f8d-bd4eb21ab1ef.png">

Or do you want them to be displayed on another location?

**Comment by PhilETaylor** [comment]
hmmm I was looking on this page

https://volunteers.joomla.org/teams/user-experience-working-group

I guess I missed the fact I need to make 3 more clicks and click a Contact tab just to view someones Github handle... plus the words "connect on github" sounds more like a login link than a link to someones github profile page! 

Ironically @cpfeifer has already told me that I am "expecting too much of him" to make any "decisions" on UX (for which he is the team lead)... so I doubt this UX fail with change either...

**Comment by ghost** [comment]
My apologies if I was not able to address this UX issue to your satisfaction. It's most likely because I'm not part of the volunteer portal team and I didn't know the issue existed until you politely pointed it out to me. 

We're happy to help the volunteer portal team upon request, however, it is very difficult for us to address issues we have no knowledge of for projects we are not involved with. Thank you for understanding.

**Comment by PhilETaylor** [comment]
Whatever Cliff 
Like you said before, asking you to make decisions on UX for the project as team lead is "expecting too much" from you!
I, like a lot of people, have given up on you and your team. Time will tell if anything other than words and excuses come from you and your "team"

**Comment by sanderpotjer** [comment]
@PhilETaylor do you expect to see just the GitHub handle on the members overview of a team or also the other contact/social channels?

Do you have a suggestion for a text other then "Connect on GitHub" that would make it more clear for you?

Thanks!

**Comment by PhilETaylor** [comment]
For a start a visitor has to register for an account and be logged in before they can currently see the contents of the Contact tabs... 

When I login Im taken to MY page and not the page I was on when I logged in - another fail. 

Then I click back and I now see a confusing bold list of services at the bottom - one could confuse those as being services associated to this user - when in fact they are the "share" icons.

Instead of "Connect on" the text could be something more helpful like "View Cliff's GitHub Profile". The word "connect" means different things to different people. "Connect"ing a service to another service is what I read it as, as you often do this with social services.

Lastly there is a confirmed security issue with the contact form. I'll raise that in the JSST.

**Comment by sanderpotjer** [comment]
@PhilETaylor thanks for your positive way of bringing feedback!

- The contact tab has been made visible for logged in users on request in the past, to prevent spam etc..
- The login redirect will be fixed
- The social share buttons are added on request too, I don't like the style either, but those are the default share icons that are used across the Joomla sites
- Thanks for the wording suggestion
- Could you send me a copy of the security issue by email too?

Thanks and have a great day!

**Comment by PhilETaylor** [comment]
Why should I have to be logged in just to get a link to someone's twitter or github account name? No reason for that. 

Just because people request things doesnt mean they are right - thats why the project has a UX team and website leadership teams...

**Comment by mbabker** [comment]
When the contact list was just showing everyone's email addresses, I think that had reason to restrict what all information was displayed publicly.  Now it's a contact form so that's less of an issue.  Honestly, I don't see the need to restrict the full contact tab to logged in users only since most of it is people's usual "Find me at X place" stuff anyway.

Spam issue for the contact forms.  Throw a captcha in front of it.  Honestly, most of the spam that comes to the `security@joomla.org` address these days is a result of direct email (and usually gets picked up by Google's filters), I can't recall the last time the form at https://developer.joomla.org/security/contact-the-team.html was used for spam purposes.

Implementing that can open the discussion for whether it'd be acceptable to make the contact forms public.

As for the share icons, honestly I don't believe they need to be on the individual profile and team pages.  They definitely belong with reports though.  It'd be the same as if we had those icons at https://developer.joomla.org/security.html or https://www.joomla.org/core-features.html in that they'd just be out of place.

**Comment by ghost** [comment]
I agree with the decision to make the contact information private, I think if you want to interact with the volunteer community then you should have an account.

I think the individuals website / git / social media buttons would be better with simply the name of the channel: Twitter, Facebook etc, the "Connect on" isn't necessary. It's already a button which indicates it's a link. Adding some color to the buttons based on the channel would provide more visual direction as well.

The contact tab, all the tabs in general, tend to hide information away. Tabs save vertical space, but a downside to simple text tabs is that they don't draw much visual attention. However, this is a standard Joomla layout and design both here and in the admin interface so it's not easily changed.

The tabs are a perfect example of why a UX team needs time to process improvements before making decisions. I'm not sure tab layouts are the best solution for everything in Joomla, but it's so deeply ingrained in the core that any changes made will have wide sweeping effects on the platform and community. Think what you want about me, but if we don't consider everything and make careful decisions we're not doing our job properly, and there is a lot to consider with every decision.

**Comment by sanderpotjer** [comment]
Improvements have been made based on the feedback, thanks for that.

**Comment by ghost** [comment]
Awesome, thank you :)
