### ISSUE TITLE
Change sender address

### ISSUE THREAD

**Issue by sanderpotjer** [joomla/volunteers.joomla.org#75]
From the one that submitted the contact form to default `admin_no_reply@joomla.org`, but reply mail set to the sender email.

**Comment by zero-24** [comment]
There is a setting in joomla for the reply mail is volunteers not a standalone install?

**Comment by mbabker** [comment]
The code is setting the sender address.  Honestly, if you just remove https://github.com/joomla/volunteers.joomla.org/blob/cc3ff0248356c5340aacd71711fa2d06f8bf9ea2/www/components/com_volunteers/controllers/team.php#L175 you should be fine since the mailer created in `JFactory` uses the global config for the sender address (which for the `joomla.org` properties should usually be admin@joomla.org or no-reply@joomla.org).
